### ISSUE TITLE
Lors de la sélection d'une valeur dans une liste déroulante, la liste ne se ferme pas, et l'autre liste n'apparait pas automatiquement

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/SimSemSearch#20]
Fonctionne bien dans la page de test, mais ne fonctionne pas dans la page où j'ai intégré le composant.
Note : les icônes ne sont pas chargés, ça peut avoir un effet de bord ?

**Comment by antoine37120** [comment]
@tfrancart : Pas d'effet de bord à prévoir. Par contre j'aimerait pouvoir étudier ce bug dans le conditions ou il apparaît. As tu une page de test en ligne ?

**Comment by tfrancart** [comment]
Non pas en ligne mais je te montrerai. J'ai peut-être oublié quelque chose dans l'intégration du composant, même si j'ai bien repointé plusieurs fois.

**Comment by tfrancart** [comment]
Voir #29

**Comment by tfrancart** [comment]
Réglé avec la bonne version de nice-query
