### ISSUE TITLE
Est-il possible de faire un bundle en un seul fichier js qui comprend toutes les dépendances (easyautocomplte + nice-select) ?

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/SimSemSearch#26]
+ sparql-js

**Comment by antoine37120** [comment]
Tout est regroupé dans simsemsearch.js et le css global du projet

**Comment by antoine37120** [comment]
@tfrancart : je viens de trouver comment compiler les fichier en plusieurs versions disponibles (minimifié et non minimifiés)
Je testerais cela plus tard de re-dispatcher les scripts

**Comment by antoine37120** [comment]
J'ai finalement revu la solution permettant de regrouper le contenus des fichiers en un seul et de les minimifier.

**Comment by tfrancart** [comment]
cf uglify.sh
