### ISSUE TITLE
jquery.nice-select.js : modifications

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/SimSemSearch#34]
jquery.nice-select.js a été modifié pour l'insertion des icônes et la fermeture des listes.
Il faut documenter cela pour l'intégration du composant dans la page; idéalement faire un "bundle" de tout le code à insérer dans la page en un seul fichier. Voir #26

Note : je ne trouve pas d'indication de license de nice-select (https://github.com/hernansartorio/jquery-nice-select)

**Comment by antoine37120** [comment]
Jquery nice select est maintenant supprimé et le js et css nécessaire sont regroupés avec ceux du projet.
Tout est donc maintenant dans un seul fichier js et css (scss)
