### ISSUE TITLE
Nouvel icône de maison

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/SimSemSearch#56]
On va ajuster un petit peu les specs du composant de recherche. Il y aura un nouveau type d'objet "entité archéologique" pour laquelle il faudra introduire un icône de maison. Je vous fais une proposition d'icône. Sébastien pourra s'occuper de le rendre propre et de l'intégrer ?

**Comment by tfrancart** [comment]
Voici l'icône. Merci !

![ison_maison](https://user-images.githubusercontent.com/2728945/51614421-eb184c80-1f25-11e9-9432-fde5891aac4e.png)

**Comment by antoine37120** [comment]
Salut Thomas,

C'est envoyé à Sebastien.

Tu devrais tester les derniers commits, ça commence à être sympas ;)



-- 

Antoine DUPRÉ
DT | Developpeur
antoine@mwebius.com
06 45 37 44 13

MWEBIUS PROJECTCréateurs d'échange durable
Agence de Communication Visuelle
30 rue André Theuriet | 37000 TOURS
www.mwebiusproject.com





Le mer. 23 janv. 2019 à 15:45, Thomas Francart <notifications@github.com> a
écrit :

**Comment by antoine37120** [comment]
Je viens de t'envoyer un mail avec les nouveaux icons de la maison
