### ISSUE TITLE
TimeWidget : taille de la zone de recherche + placeholder

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/SimSemSearch#64]
La zone de recherche du TimeWidget est devenu trop petite.
Par ailleurs on ne sait pas qu'on peut rechercher dans la première zone et entrer des années dans les 2ème et 3ème zone.
Il faudrait agrandir la 1ère zone et mettre si possible un placeholder "nom de la période..." dans cette zone
Voir copie d'écran :

![image](https://user-images.githubusercontent.com/2728945/51741257-baa3f000-2096-11e9-8043-09037f8f3b93.png)

**Comment by antoine37120** [comment]
Erreur de ma par sur la notation du commit 92b79e8 améliorant l'ergonomie du widget et bug rencontrés
