### ISSUE TITLE
On ne récupère plus le SPARQL sur des requêtes sans valeurs : "Site a trouvé Mobilier"

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/SimSemSearch#70]
Le SPARQL n'est plus généré quand on fait "Site a trouvé Mobilier" mais qu'on ne sélectionne pas de valeurs. Avant cela fonctionnait.

**Comment by antoine37120** [comment]
J'ai ajouté dans les settings du module : 
WidgetsNeedValueIds: ['http://ontologies.sparna.fr/SimSemSearch#SearchWidget', 'http://ontologies.sparna.fr/SimSemSearch#TimeWidget'] ,

**Comment by tfrancart** [comment]
On pourrait hardcoder cela sans avoir besoin de le paramétrer
