### ISSUE TITLE
Limitation de profondeur à 3 : peut-on augmenter cette limite ?

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/SimSemSearch#74]
Est-ce possible facilement ? est-ce que ça pose des problèmes dans l'interface ?

**Comment by antoine37120** [comment]
Oui, c'est possible (en 30 minutes). Nous pouvons l'ajouter comme paramètre. Cela peu être inclus pour la v2

**Comment by tfrancart** [comment]
OK pour l'inclure pour la v2, avce l'ajout d'un nouveau paramètre "maxDepth". Si non spécifié, utiliser 3 comme profondeur max par défaut. Merci !
