### ISSUE TITLE
TimeWidget : ne pas autoriser d'ajouter la valeur en cliquant sur "Add" si on n'a rien rempli (ni début, ni fin)

### ISSUE THREAD

**Issue by tfrancart** [sparna-git/SimSemSearch#81]

**Comment by antoine37120** [comment]
J'ai ajouté un test pour éviter que la date de début soit plus grand que date de fin.
Ce qui autorise 2 années identiques, et donc fera par exemple  
FILTER((?Temps1 > "1920-01-01"^^xsd:dateTime) && (?Temps1 <= "1920-12-31"^^xsd:dateTime))
